[package]
name = "telegraph"
version = "0.1.1"
authors = ["Safort <a.asafort@gmail.com>"]
repository = "https://github.com/Safort/telegraph"
description = "Unofficial Telegraph library"
license = "MIT"

[dependencies]
hyper = "0.9"
serde = "0.9"
serde_json = "0.9"
serde_derive = "0.9"