[package]
name = "telegraph"
version = "0.1.0"
authors = ["Safort <a.asafort@gmail.com>"]
description = "Unofficial Telegraph library"
license = "MIT"
repository = ""

[dependencies]
hyper = "0.9"
rustc-serialize = "0.3"
serde = "0.8"
serde_json = "0.8"
serde_derive = "0.8"